/*
 * Copyright (c) 2016 Samsung Electronics Co., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

#ifndef _SENSOR_COMMON_H_
#define _SENSOR_COMMON_H_

#define SENSOR_EVENT_SHIFT 16
#define RAW_DATA_EVENT 0x0001

#define UNKNOWN_NAME "UNKNOWN"

enum sensorhub_enable_bit {
	SENSORHUB_ACCELEROMETER_ENABLE_BIT = 0,
	SENSORHUB_GYROSCOPE_ENABLE_BIT,
	SENSORHUB_GEOMAGNETIC_UNCALIB_ENABLE_BIT,
	SENSORHUB_GEOMAGNETIC_RAW_ENABLE_BIT,
	SENSORHUB_GEOMAGNETIC_ENABLE_BIT,
	SENSORHUB_PRESSURE_ENABLE_BIT,
	SENSORHUB_GESTURE_ENABLE_BIT,
	SENSORHUB_PROXIMITY_ENABLE_BIT,
	SENSORHUB_TEMPERATURE_HUMIDITY_ENABLE_BIT,
	SENSORHUB_LIGHT_ENABLE_BIT,
	SENSORHUB_PROXIMITY_RAW_ENABLE_BIT,
	SENSORHUB_ORIENTATION_ENABLE_BIT,
	SENSORHUB_STEP_DETECTOR_ENABLE_BIT = 12,
	SENSORHUB_SIG_MOTION_ENABLE_BIT,
	SENSORHUB_GYRO_UNCALIB_ENABLE_BIT,
	SENSORHUB_GAME_ROTATION_VECTOR_ENABLE_BIT = 15,
	SENSORHUB_ROTATION_VECTOR_ENABLE_BIT,
	SENSORHUB_STEP_COUNTER_ENABLE_BIT,
	SENSORHUB_HRM_RAW_ENABLE_BIT,
	SENSORHUB_HRM_RAW_FAC_ENABLE_BIT,
	SENSORHUB_HRM_LIB_ENABLE_BIT,
	SENSORHUB_TILT_MOTION,
	SENSORHUB_UV_SENSOR,
	SENSORHUB_PIR_ENABLE_BIT,
	SENSORHUB_PIR_RAW_ENABLE_BIT,
	SENSORHUB_GSR_ENABLE_BIT = 25,
	SENSORHUB_ENABLE_BIT_MAX,
};

#endif /* _SENSOR_COMMON_H_ */
